# Generated by Django 5.0.7 on 2025-08-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadicomdigital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('ACCOUNTING', 'Perakaunan'), ('PAYROLL', 'Penggajian'), ('POS', 'Sistem POS'), ('EINVOICE', 'E-Invoice')], max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
