# Generated by Django 5.0.7 on 2025-08-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadicomdigital', '0003_alter_service_options_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Penuh')),
                ('position', models.CharField(max_length=100, verbose_name='Jawatan')),
                ('bio', models.TextField(blank=True, verbose_name='Biografi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Gambar Profil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Susunan')),
            ],
            options={
                'verbose_name': 'Ahli Pasukan',
                'verbose_name_plural': 'Ahli Pasukan',
                'ordering': ['order', 'name'],
            },
        ),
    ]
