# Generated by Django 5.0.7 on 2025-08-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadicomdigital', '0004_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tajuk Gambar')),
                ('image', models.ImageField(help_text='Upload gambar untuk galeri', upload_to='gallery/%Y/%m/%d/', verbose_name='Gambar')),
                ('description', models.TextField(blank=True, help_text='Penerangan ringkas tentang gambar', verbose_name='Penerangan')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Tarikh Upload')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Susunan')),
            ],
            options={
                'verbose_name': 'Gambar Galeri',
                'verbose_name_plural': 'Galeri Gambar',
                'ordering': ['order', '-upload_date'],
            },
        ),
    ]
