# Generated by Django 5.0.7 on 2025-08-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadicomdigital', '0005_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Kategori Blog',
                'verbose_name_plural': 'Kategori Blog',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tajuk Blog')),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(verbose_name='Kandungan')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='Ringkasan')),
                ('featured_image', models.ImageField(upload_to='blog/%Y/%m/', verbose_name='Gambar Utama')),
                ('author', models.CharField(default='Admin Nadicom', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, to='nadicomdigital.blogcategory')),
            ],
            options={
                'verbose_name': 'Post Blog',
                'verbose_name_plural': 'Post Blog',
                'ordering': ['-published_date'],
            },
        ),
    ]
