# Generated by Django 5.0.7 on 2025-08-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadicomdigital', '0006_blogcategory_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Jumlah Paparan'),
        ),
    ]
