# Generated by Django 5.0.7 on 2025-08-25 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadicomdigital', '0008_alter_blogpost_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tajuk', models.CharField(max_length=200)),
                ('tarikh', models.DateField()),
                ('masa_mula', models.TimeField()),
                ('masa_tamat', models.TimeField()),
                ('lokasi', models.CharField(max_length=300)),
                ('kapasiti', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('AKTIF', 'Aktif'), ('TIDAK_AKTIF', 'Tidak Aktif')], default='AKTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('no_ic', models.CharField(max_length=20)),
                ('syarikat', models.CharField(max_length=100)),
                ('no_telefon', models.CharField(max_length=17)),
                ('email', models.EmailField(max_length=254)),
                ('dihantar_pada', models.DateTimeField(auto_now_add=True)),
                ('disahkan', models.BooleanField(default=False)),
                ('emel_dihantar', models.BooleanField(default=False)),
                ('kursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nadicomdigital.kursus')),
            ],
        ),
    ]
