# Generated by Django 5.0.7 on 2025-08-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadicomdigital', '0009_kursus_peserta'),
    ]

    operations = [
        migrations.AddField(
            model_name='peserta',
            name='tarikh_emel_dihantar',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='peserta',
            unique_together={('email', 'kursus')},
        ),
    ]
