# Generated by Django 5.0.7 on 2025-09-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadicomdigital', '0010_peserta_tarikh_emel_dihantar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('TUTORIAL', 'Tutorial'), ('TESTIMONIAL', 'Testimonial'), ('PRODUCT_DEMO', 'Product Demo'), ('WEBINAR', 'Webinar'), ('INTRODUCTION', 'Pengenalan')], default='TUTORIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
