# Generated by Django 5.0.7 on 2025-09-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadicomdigital', '0011_video_category_video_view_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('SQL_ACCOUNTING', 'SQL Accounting'), ('E_INVOICE', 'E-Invoice'), ('DIGITAL_PAYMENT', 'Digital Payment'), ('POS_SYSTEM', 'POS System'), ('PAYROLL', 'Payroll System'), ('INVENTORY', 'Inventory Management'), ('HR_MODULE', 'HR Module'), ('SETUP_CONFIG', 'Setup & Configuration'), ('USER_MANAGEMENT', 'User Management'), ('REPORTING', 'Reporting & Analytics'), ('TROUBLESHOOTING', 'Troubleshooting'), ('NEW_FEATURES', 'New Features'), ('TUTORIAL', 'Tutorial'), ('WEBINAR', 'Webinar'), ('ANNOUNCEMENT', 'Announcement'), ('TESTIMONIAL', 'Testimonial')], default='TUTORIAL', max_length=20),
        ),
    ]
