# Generated by Django 5.0.7 on 2025-09-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadicomdigital', '0012_alter_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('SQL_ACCOUNTING', 'SQL Accounting'), ('E_INVOICE', 'E-Invoice'), ('DIGITAL_PAYMENT', 'Digital Payment'), ('POS_SYSTEM', 'POS System'), ('PAYROLL', 'Payroll System')], default='TUTORIAL', max_length=20),
        ),
    ]
