# Generated by Django 5.0.7 on 2025-09-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadicomdigital', '0013_alter_video_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='view_count',
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('SQL_ACCOUNTING', 'SQL Accounting'), ('E_INVOICE', 'E-Invoice'), ('DIGITAL_PAYMENT', 'Digital Payment'), ('POS_SYSTEM', 'POS System'), ('PAYROLL', 'Payroll System'), ('UNCATEGORIZED', 'Uncategorized')], default='UNCATEGORIZED', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
