# Generated by Django 5.0.7 on 2025-10-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nadicomdigital', '0015_video_view_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Ahli Pasukan', 'verbose_name_plural': 'Ahli Pasukan'},
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='order',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='position',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(upload_to='team/'),
        ),
    ]
