# Generated by Django 5.0.7 on 2025-11-01 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nadicomdigital', '0016_alter_teammember_options_remove_teammember_bio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
